/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabriel
 */
public class Prog extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    private ArrayList<Ins> buf;
    /**
     * Creates new form Prog
     */
    public Prog() {
        initComponents();
        dtm = new DefaultTableModel();
        dtm.addColumn("Comando");
        jTable1.setModel(dtm);
        buf = new ArrayList<>();
        fillTable();
        if(XBeeWiFiControl.getDevices() != null){
            for(XBeeWiFi d : XBeeWiFiControl.getDevices()){
                jComboBox5.addItem(d.getAddr64().toString());
                jComboBox6.addItem(d.getAddr64().toString());
                jComboBox7.addItem(d.getAddr64().toString());
                jComboBox8.addItem(d.getAddr64().toString());
            }
        }
        jComboBox8.addItem("GLOBAL");
        //carregar as portas para o combo
        //incluir delay como instrução
        //incluir possibilidade de executar sem leitura
    }
    
    private void fillTable(){
        if(Exec.getIns() != null){
            for(Ins p : Exec.getIns()){
                if(p instanceof ConIns){
                    ConIns in = (ConIns) p;
                    dtm.addRow(new Object[] {(in.isGlobal()?"[G]":"")+"Se porta "+in.getPortIn()+" em ["+XBeeWiFiControl.getDevice(in.getReadDevice()).getName()+"] "+in.getOprd()+" "+in.getConV()+" então porta "+in.getPortOut()+" em ["+XBeeWiFiControl.getDevice(in.getWriteDevice()).getName()+"]  -> "+(in.getSetV() ? "HIGH" : "LOW")});
                } else {
                    if(p instanceof LogIns){
                        LogIns li = (LogIns) p;
                        dtm.addRow(new Object[] {(li.isGlobal()?"[G]":"")+"Log da porta em ["+XBeeWiFiControl.getDevice(li.getAddr()).getName()+"] "+li.getPort()+" no arquivo "+li.getNomeArq()});
                    } else {
                        Delay dl = (Delay) p;
                        dtm.addRow(new Object[] {"Delay de "+ dl.getTime() +"ms em ["+XBeeWiFiControl.getDevice(dl.getAddr()).getName()+"]"});
                    }
                }
            }
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        rHigh = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        rCmd = new javax.swing.JRadioButton();
        rDelay = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Dispositivo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jLabel2.setText("Opr.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">", "<", "=" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 58, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 58, -1));

        jLabel3.setText("Valor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "D0", "D1", "D2", "D3", "D4", "D5", "D6", "D7" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, -1, -1));

        jLabel4.setText("Porta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, -1, -1));

        jLabel5.setText("Valor");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 785, 224));

        jButton1.setText("Incluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 70, -1));

        buttonGroup1.add(rHigh);
        rHigh.setSelected(true);
        rHigh.setText("High");
        getContentPane().add(rHigh, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Low");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, -1, -1));

        buttonGroup2.add(rCmd);
        rCmd.setSelected(true);
        rCmd.setText("Controle");
        getContentPane().add(rCmd, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 66, -1, -1));

        buttonGroup2.add(rDelay);
        rDelay.setText("Delay");
        getContentPane().add(rDelay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 44, -1));

        jLabel6.setText("ms");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 70, -1));

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("Log");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7" }));
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 117, -1));

        jLabel7.setText("Arquivo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 159, -1));

        getContentPane().add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 159, -1));

        getContentPane().add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 159, -1));

        jLabel8.setText("Porta");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jLabel9.setText("Dispositivo");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel10.setText("Dispositivo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 70, -1));

        jCheckBox1.setText("Global");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, -1, -1));

        jCheckBox2.setText("Global");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, -1, -1));

        getContentPane().add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 159, -1));

        jLabel11.setText("Dispositivo");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(rCmd.isSelected()){
            int s;
            if(jTextField1.getText().equals("")){
                s = -1;
            } else {
                s = Integer.parseInt(jTextField1.getText());
            }
            boolean global = jCheckBox2.isSelected();
            buf.add(new ConIns(XBeeWiFiControl.getDevice(jComboBox6.getSelectedIndex()).getAddr64().toString(), XBeeWiFiControl.getDevice(jComboBox7.getSelectedIndex()).getAddr64().toString(), jComboBox1.getSelectedIndex(), jComboBox3.getSelectedItem().toString(), jComboBox2.getSelectedItem().toString(), s, rHigh.isSelected(), global));
            
            /*if(s != -1){
                dtm.addRow(new Object[] {(global?"[G]":"")+"Se porta "+jComboBox1.getSelectedItem()+" "+jComboBox2.getSelectedItem()+" "+jTextField1.getText()+" então porta "+jComboBox3.getSelectedItem()+" -> "+(rHigh.isSelected() ? "HIGH" : "LOW")}); 
            } else {
                dtm.addRow(new Object[] {(global?"[G]":"")+"Porta "+jComboBox3.getSelectedItem()+" -> "+(rHigh.isSelected() ? "HIGH" : "LOW")}); 
            }*/
        } else {
            if(rDelay.isSelected()){
                buf.add(new Delay(Integer.parseInt(jTextField2.getText()), jComboBox8.getSelectedItem().toString()));
                //dtm.addRow(new Object[] {"Delay em "+Integer.parseInt(jTextField2.getText())+"ms"});
                
            } else { //Log
                boolean global = jCheckBox1.isSelected();
                buf.add(new LogIns(XBeeWiFiControl.getDevice(jComboBox5.getSelectedIndex()).getAddr64().toString(), jComboBox4.getSelectedIndex(), jTextField3.getText(), global));
                //dtm.addRow(new Object[] {(global?"[G]":"")+"Log da porta "+jComboBox4.getSelectedIndex()+" no arquivo "+jTextField3.getText()});
            }
        }
        Exec.addIns(buf.get(0));
        buf.remove(0);
        
        dtm.setRowCount(0); //atualizando a tabela
        fillTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /*for(Object i : buf){
            Exec.addIns(i);
        }*/
        DataLoader.save(XBeeWiFiControl.SAVE_FILE, Exec.getIns());
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int index = jTable1.getSelectedRow();
        if(index != -1){
            Exec.removeIns(index);
            dtm.setRowCount(0);
            fillTable();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JRadioButton rCmd;
    private javax.swing.JRadioButton rDelay;
    private javax.swing.JRadioButton rHigh;
    // End of variables declaration//GEN-END:variables
}
