/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author gabriel
 */
public class ZigBeeOutputs extends javax.swing.JFrame implements ActionListener {

    private final int DELAY = 10000;
    
    private final XBeeWiFi device;
    
    private int SIO; // I/O sum
    private int SEA; // Analog inputs sum
    private int SSA; // Actived Outputs
    private int[] inputValues;
    
    public ZigBeeOutputs(XBeeWiFi device) {
        initComponents();
        this.device = device;
        Timer timer = new Timer(DELAY, this);
        timer.setInitialDelay(20);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        b0ON = new javax.swing.JButton();
        b0OFF = new javax.swing.JButton();
        b1ON = new javax.swing.JButton();
        b1OFF = new javax.swing.JButton();
        b2ON = new javax.swing.JButton();
        b2OFF = new javax.swing.JButton();
        b3ON = new javax.swing.JButton();
        b3OFF = new javax.swing.JButton();
        b6ON = new javax.swing.JButton();
        b6OFF = new javax.swing.JButton();
        b5ON = new javax.swing.JButton();
        b5OFF = new javax.swing.JButton();
        b7ON = new javax.swing.JButton();
        b7OFF = new javax.swing.JButton();
        b4ON = new javax.swing.JButton();
        b4OFF = new javax.swing.JButton();
        AD0Value = new javax.swing.JLabel();
        AD1Value = new javax.swing.JLabel();
        AD2Value = new javax.swing.JLabel();
        AD3Value = new javax.swing.JLabel();
        AD6Value = new javax.swing.JLabel();
        AD5Value = new javax.swing.JLabel();
        AD7Value = new javax.swing.JLabel();
        AD4Value = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/gabriel/Documentos/BicJr/xbee-IO-pins.jpg")); // NOI18N

        b0ON.setText("ON");
        b0ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ONActionPerformed(evt);
            }
        });

        b0OFF.setText("OFF");
        b0OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0OFFActionPerformed(evt);
            }
        });

        b1ON.setText("ON");
        b1ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ONActionPerformed(evt);
            }
        });

        b1OFF.setText("OFF");
        b1OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1OFFActionPerformed(evt);
            }
        });

        b2ON.setText("ON");
        b2ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ONActionPerformed(evt);
            }
        });

        b2OFF.setText("OFF");
        b2OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2OFFActionPerformed(evt);
            }
        });

        b3ON.setText("ON");
        b3ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ONActionPerformed(evt);
            }
        });

        b3OFF.setText("OFF");
        b3OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3OFFActionPerformed(evt);
            }
        });

        b6ON.setText("ON");
        b6ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ONActionPerformed(evt);
            }
        });

        b6OFF.setText("OFF");
        b6OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6OFFActionPerformed(evt);
            }
        });

        b5ON.setText("ON");
        b5ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ONActionPerformed(evt);
            }
        });

        b5OFF.setText("OFF");
        b5OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5OFFActionPerformed(evt);
            }
        });

        b7ON.setText("ON");
        b7ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ONActionPerformed(evt);
            }
        });

        b7OFF.setText("OFF");
        b7OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7OFFActionPerformed(evt);
            }
        });

        b4ON.setText("ON");
        b4ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ONActionPerformed(evt);
            }
        });

        b4OFF.setText("OFF");
        b4OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4OFFActionPerformed(evt);
            }
        });

        AD0Value.setText("AD0");

        AD1Value.setText("AD1");

        AD2Value.setText("AD2");

        AD3Value.setText("AD3");

        AD6Value.setText("AD6");

        AD5Value.setText("AD5");

        AD7Value.setText("AD7");

        AD4Value.setText("AD4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b0ON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b0OFF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AD0Value))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b1ON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b1OFF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AD1Value))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b2ON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b2OFF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AD2Value))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b3ON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b3OFF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AD3Value))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b6ON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b6OFF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AD6Value))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b4ON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b4OFF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AD4Value))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b5ON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b5OFF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AD5Value))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b7ON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b7OFF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AD7Value)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b0ON)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b0OFF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AD0Value)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1ON)
                    .addComponent(b1OFF)
                    .addComponent(AD1Value))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b2ON)
                    .addComponent(b2OFF)
                    .addComponent(AD2Value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b3ON)
                    .addComponent(b3OFF)
                    .addComponent(AD3Value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b6ON)
                    .addComponent(b6OFF)
                    .addComponent(AD6Value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b5ON)
                    .addComponent(b5OFF)
                    .addComponent(AD5Value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b7ON)
                    .addComponent(b7OFF)
                    .addComponent(AD7Value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b4ON)
                    .addComponent(b4OFF)
                    .addComponent(AD4Value))
                .addGap(96, 96, 96))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b0ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ONActionPerformed
        XBeeWiFi.setDigitalOutput(device, 0, true);
    }//GEN-LAST:event_b0ONActionPerformed

    private void b0OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0OFFActionPerformed
        XBeeWiFi.setDigitalOutput(device, 0, false);
    }//GEN-LAST:event_b0OFFActionPerformed

    private void b1ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ONActionPerformed
        XBeeWiFi.setDigitalOutput(device, 1, true);
    }//GEN-LAST:event_b1ONActionPerformed

    private void b1OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1OFFActionPerformed
        XBeeWiFi.setDigitalOutput(device, 1, false);
    }//GEN-LAST:event_b1OFFActionPerformed

    private void b2ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ONActionPerformed
        XBeeWiFi.setDigitalOutput(device, 2, true);
    }//GEN-LAST:event_b2ONActionPerformed

    private void b2OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2OFFActionPerformed
        XBeeWiFi.setDigitalOutput(device, 2, false);
    }//GEN-LAST:event_b2OFFActionPerformed

    private void b3ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ONActionPerformed
        XBeeWiFi.setDigitalOutput(device, 3, true);
    }//GEN-LAST:event_b3ONActionPerformed

    private void b3OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3OFFActionPerformed
        XBeeWiFi.setDigitalOutput(device, 3, false);
    }//GEN-LAST:event_b3OFFActionPerformed

    private void b6ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ONActionPerformed
        XBeeWiFi.setDigitalOutput(device, 6, true);
    }//GEN-LAST:event_b6ONActionPerformed

    private void b6OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6OFFActionPerformed
        XBeeWiFi.setDigitalOutput(device, 6, false);
    }//GEN-LAST:event_b6OFFActionPerformed

    private void b5ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ONActionPerformed
        XBeeWiFi.setDigitalOutput(device, 5, true);
    }//GEN-LAST:event_b5ONActionPerformed

    private void b5OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5OFFActionPerformed
        XBeeWiFi.setDigitalOutput(device, 5, false);
    }//GEN-LAST:event_b5OFFActionPerformed

    private void b7ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ONActionPerformed
        XBeeWiFi.setDigitalOutput(device, 7, true);
    }//GEN-LAST:event_b7ONActionPerformed

    private void b7OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7OFFActionPerformed
        XBeeWiFi.setDigitalOutput(device, 7, false);
    }//GEN-LAST:event_b7OFFActionPerformed

    private void b4ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ONActionPerformed
        XBeeWiFi.setDigitalOutput(device, 4, true);
    }//GEN-LAST:event_b4ONActionPerformed

    private void b4OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4OFFActionPerformed
        XBeeWiFi.setDigitalOutput(device, 4, false);
    }//GEN-LAST:event_b4OFFActionPerformed

    @Override
    public void actionPerformed(ActionEvent e) {
        int counter;
        int[] inputs;
        int[] state;
        state = XBeeWiFi.readIOState(device);
        SIO = state[0];
        SEA = state[1];
        SSA = state[2];
        // setting      (buttons active)      (output states)
        b0ON.setEnabled(portState(SIO, 0) && !portState(SSA, 0));
        b0OFF.setEnabled(portState(SIO, 0) && portState(SSA, 0));
        b1ON.setEnabled(portState(SIO, 1) && !portState(SSA, 1));
        b1OFF.setEnabled(portState(SIO, 1) && portState(SSA, 1));
        b2ON.setEnabled(portState(SIO, 2) && !portState(SSA, 2));
        b2OFF.setEnabled(portState(SIO, 2) && portState(SSA, 2));
        b3ON.setEnabled(portState(SIO, 3) && !portState(SSA, 3));
        b3OFF.setEnabled(portState(SIO, 3) && portState(SSA, 3));
        b4ON.setEnabled(portState(SIO, 4) && !portState(SSA, 4));
        b4OFF.setEnabled(portState(SIO, 4) && portState(SSA, 4));
        b5ON.setEnabled(portState(SIO, 5) && !portState(SSA, 5));
        b5OFF.setEnabled(portState(SIO, 5) && portState(SSA, 5));
        b6ON.setEnabled(portState(SIO, 6) && !portState(SSA, 6));
        b6OFF.setEnabled(portState(SIO, 6) && portState(SSA, 6));
        b7ON.setEnabled(portState(SIO, 7) && !portState(SSA, 7));
        b7OFF.setEnabled(portState(SIO, 7) && portState(SSA, 7));
        
        //setting input values
        inputs = new int[state.length-3];
        for(int i = 0; i < inputs.length; i++){
            inputs[i] = state[i+3];
        }
        counter = 0;
        if(portState(SEA, 0)){
            AD0Value.setText("AD0: "+inputs[counter]);
            counter++;
        } else {
            AD0Value.setText("");
        }
        if(portState(SEA, 1)){
            AD1Value.setText("AD1: "+inputs[counter]);
            counter++;
        } else {
            AD1Value.setText("");
        }
        if(portState(SEA, 2)){
            AD2Value.setText("AD2: "+inputs[counter]);
            counter++;
        } else {
            AD2Value.setText("");
        }
        if(portState(SEA, 3)){
            AD3Value.setText("AD3: "+inputs[counter]);
            counter++;
        } else {
            AD3Value.setText("");
        }
        if(portState(SEA, 4)){
            AD4Value.setText("AD4: "+inputs[counter]);
            counter++;
        } else {
            AD4Value.setText("");
        }
        if(portState(SEA, 5)){
            AD5Value.setText("AD5: "+inputs[counter]);
            counter++;
        } else {
            AD5Value.setText("");
        }
        if(portState(SEA, 6)){
            AD6Value.setText("AD6: "+inputs[counter]);
            counter++;
        } else {
            AD6Value.setText("");
        }
        if(portState(SEA, 7)){
            AD7Value.setText("AD7: "+inputs[counter]);
            counter++;
        } else {
            AD7Value.setText("");
        }
        //refresh end
    }
    
    private boolean portState(int sum, int n){
        return ((sum/(int)Math.pow(2, n))%2 == 1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AD0Value;
    private javax.swing.JLabel AD1Value;
    private javax.swing.JLabel AD2Value;
    private javax.swing.JLabel AD3Value;
    private javax.swing.JLabel AD4Value;
    private javax.swing.JLabel AD5Value;
    private javax.swing.JLabel AD6Value;
    private javax.swing.JLabel AD7Value;
    private javax.swing.JButton b0OFF;
    private javax.swing.JButton b0ON;
    private javax.swing.JButton b1OFF;
    private javax.swing.JButton b1ON;
    private javax.swing.JButton b2OFF;
    private javax.swing.JButton b2ON;
    private javax.swing.JButton b3OFF;
    private javax.swing.JButton b3ON;
    private javax.swing.JButton b4OFF;
    private javax.swing.JButton b4ON;
    private javax.swing.JButton b5OFF;
    private javax.swing.JButton b5ON;
    private javax.swing.JButton b6OFF;
    private javax.swing.JButton b6ON;
    private javax.swing.JButton b7OFF;
    private javax.swing.JButton b7ON;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    
}
